In [1]:
import numpy as np

Training (Constructing Weights)

In [2]:
states = np.array([[+1, -1, +1, -1, +1], [-1, +1, +1, -1, +1]])

# Number of states M, Number of nodes N
M = len(states) # 2
N = len(states[0]) # 5

# Construct the weight matrix
W = np.zeros((5, 5))
total = 0
for i in range(N):
    for j in range(N):
        if (i != j):
            total = (states[0][i] * states[0][j]) + (states[1][i] * states[1][j])
            W[i][j] = (1/N) * total
W

array([[ 0. , -0.4,  0. ,  0. ,  0. ],
       [-0.4,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. , -0.4,  0.4],
       [ 0. ,  0. , -0.4,  0. , -0.4],
       [ 0. ,  0. ,  0.4, -0.4,  0. ]])

Probing Pattern

In [3]:
initial_input_state = np.array([+1, +1, +1, +1, +1])

Dynamic Evolution

In [7]:
# Hard-limiting non-linearity function
f_h = np.vectorize(lambda x: 1 if x >= 0 else -1)

# Dynamic evolution
def evolve(order, log=False): 
    t = 0
    last_U = None
    U = initial_input_state.copy()
    if log:
        print('U({}) = {}'.format(t, U))
        
    # Until convergence
    while not np.array_equal(U, last_U):
        t += 1
        last_U = U.copy()
        # Update the nodes in order
        for i in order:
            # Be sure to zero-index
            
            # YOUR CODE HERE
            total = 0
            for j in range(N):
                total += W[j][i-1]*U[j]
            
            U[i-1] = f_h(total)
            
            if log:
                print('U_{}({}) = {}'.format(i, t, U[i-1]))

        # Log U for this iteration
        if log:
            print('U({}) = {}'.format(t, U))
            None
            
    return U

In [8]:
U = evolve([3, 1, 5, 2, 4], log=True)
print(U)

U(0) = [1 1 1 1 1]
U_3(1) = 1
U_1(1) = -1
U_5(1) = 1
U_2(1) = 1
U_4(1) = -1
U(1) = [-1  1  1 -1  1]
U_3(2) = 1
U_1(2) = -1
U_5(2) = 1
U_2(2) = 1
U_4(2) = -1
U(2) = [-1  1  1 -1  1]
[-1  1  1 -1  1]


In [9]:
U = evolve([2, 4, 3, 5, 1], log=True)
print(U)

U(0) = [1 1 1 1 1]
U_2(1) = -1
U_4(1) = -1
U_3(1) = 1
U_5(1) = 1
U_1(1) = 1
U(1) = [ 1 -1  1 -1  1]
U_2(2) = -1
U_4(2) = -1
U_3(2) = 1
U_5(2) = 1
U_1(2) = 1
U(2) = [ 1 -1  1 -1  1]
[ 1 -1  1 -1  1]
